
* Interleaved Textbooks?

Some history, what this is all about...

In the past, textbooks were sometimes published as /interleaved/ editions. That meant, each page was followed by a blank page and the ambitious student/scholar had the abillity to take his notes directly in her copy of the textbook. Newton and Kant were prominent representatives of this technique [fn:blumbach].

Nowadays textbooks (or lecture material) come in PDF format. Although almost every PDF has the ability to add some notes to the PDF itself, it is not as powerfull as it could be. This is what this [[https://www.gnu.org/software/emacs/][Emacs]] minor mode tries to accomplish. It presents your PDF side by side to an [[http://orgmode.org][Org Mode]] buffer with you notes. Narrowing down to just those passages that are relevant to this paticular page in the document viewer.

In a later step it should be possible to created truly /interleaved/ PDFs with you notes.

* Intallation

tbd.

* Usage

tbd.

* License

See [[file:LICENSE][LICENSE]]

* Footnotes

[fn:blumbach] For some more information see: [[http://takingnotenow.blogspot.de/2008/07/note-keeping-in-1786-blumenbachs-system.html]]
