* Interleaved Textbooks?

Some history, what this is all about...

In the past, textbooks were sometimes published as /interleaved/ editions. That meant, each page was followed by a blank page and the ambitious student/scholar had the ability to take his notes directly in her copy of the textbook. Newton and Kant were prominent representatives of this technique [fn:blumbach].

Nowadays textbooks (or lecture material) come in PDF format. Although almost every PDF has the ability to add some notes to the PDF itself, it is not as powerful as it could be. This is what this [[https://www.gnu.org/software/emacs/][Emacs]] minor mode tries to accomplish. It presents your PDF side by side to an [[http://orgmode.org][Org Mode]] buffer with you notes. Narrowing down to just those passages that are relevant to this particular page in the document viewer.

In a later step it should be possible to created truly /interleaved/ PDFs with you notes.

* Installation

[[http://melpa.org/][MELPA]] pending.

* Usage

Create a org file that will keep your notes. In the Org header section (=#+TITLE=, =#+AUTHOR=, etc.) add

#+BEGIN_SRC
#+INTERLEAVE_PDF: /the/path/to/pdf.pdf
#+END_SRC

Then you can start *interleave-mode* by typing

#+BEGIN_SRC
M-x interleave-mode
#+END_SRC

This will display the PDF side by side to the org buffer for your notes. You can navigate the PDF as usual with <kbd>n</kbd> and <kbd>p</kbd>. Changing the page of the PDF will also narrow to the notes that are meant for this particular PDF page.

If you want to add some notes to the current page you can type <kbd>i</kbd>. This will create a new headline for your notes. If some notes are already present, <kbd>i</kbd> will swith over to the other buffer.

Typing <kbd>q</kbd> in the /DocView/ will quit *interleave-mode*.

* Footnotes

[fn:blumbach] For some more information see: [[http://takingnotenow.blogspot.de/2008/07/note-keeping-in-1786-blumenbachs-system.html]]
